Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -74,9 +74,15 @@ pipeline {
                               --docker-username=AWS \
                               --docker-password="$(aws ecr get-login-password --region ${AWS_REGION})" \
                               --docker-email=example@example.com
+                             echo "Current dir: $(pwd)"
+                             ls -lrt
 
                             sh """
+                                  echo "Current dir: $(pwd)"
+                                  echo "Files in workspace:"
                                   ls -la
+                                  echo "Files in k8s/:"
+                                  ls -la k8s || echo "Directory k8s not found"
                                   sed -i 's|539825459983.dkr.ecr.us-east-1.amazonaws.com/pet-clinic.*|539825459983.dkr.ecr.us-east-1.amazonaws.com/pet-clinic:${IMAGE_TAG}|' k8s/petclinic.yml
                             """
 
